### ISSUE TITLE
Data model: Job Page

### ISSUE THREAD

**Issue by samuellealb** [samuellealb/portfolio-nextjs-vercel#6]
**Description**
Create Job data model

**Tasks**
- [x] Create mocked data in Next
- [x] Create Data Type in Contetful
- [x] Create Sample Item

**Props**
1) title - string
2) genre - string
3) duration - number
4) location - string
5) year - number
6) category - relation
7) cover - image
8) trailer embed code - string
9) gallery - image (array)
10) sinopse - rich text
11) tech sheet - rich text
12) movie trajectory - rich text

**Current design**
N/A
