### ISSUE TITLE
Data fetch: Jobs

### ISSUE THREAD

**Issue by samuellealb** [samuellealb/portfolio-nextjs-vercel#8]
**Description**
Create Jobs data fetch service

**Tasks**
- [x] Create service in Next.js
- [x] Integrate homepage
- [x] Integrate listing page
- [x] Integrate job page
- [x] setup Static Rendering

**Props**
N/A

**Current design**
N/A
